

services:
# Database mysql
  db: 
    image: mysql
    environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: default
#     MYSQL_USER: utilisateur
#     MYSQL_PASSWORD: userpassword
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mysql-phpmyadmin
    ports:
      - 3307:3306

# Php my admin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
    networks:
      - mysql-phpmyadmin


volumes:
  db_data:

networks:
  mysql-phpmyadmin:

# docker-compose up -d
# http://localhost:8090

# docker-compose down