FROM nginx

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

RUN apt update && apt install -y git

RUN git clone https://github.com/withaarzoo/3D-Rotate-Tube .

EXPOSE 80

CMD ["nginx","-g","daemon off;"]


# Construire l'image ( sans utilise le cache)
# docker build --no-cache -t exo7 .

# test de l'image
# docker run --name testexo7 -p 5556:80 -d exo7