# Pas terminé. Pas fonctionnel pour utiliser un projet vue.js

FROM node:lts as build-stage
WORKDIR /usr/src/app
RUN apt update && apt install -y git
RUN git clone https://github.com/RoxanePouchain/Morgane-Kodalia-Photo.git/ .
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
# RUN npm run build
EXPOSE 8080
CMD [ "npm", "run build" ]

# étape de production
FROM httpd as production-stage
COPY --from=build-stage /app/dist /usr/local/apache2/htdocs
EXPOSE 80
CMD ["httpd", "-g", "daemon off;"]




