# Ne fonctionne pas. Le back se déconnecte et ne parvient pas à communiquer avec la bdd


services:
  db:
    image: mysql
    container_name: employees_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: employees_db
      MYSQL_ROOT_PASSWORD: Root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mysql-phpmyadmin-employee

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: phpmyadmin_employee
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: employees_db
    networks:
      - mysql-phpmyadmin-employee

  backapp:
    depends_on:
      - db
    build:
      context: ./back_employee
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    networks:
      - mysql-phpmyadmin-employee
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/employee

  frontapp:
    depends_on:
      - backapp
    build:
      context: ./front_employee
      dockerfile: dockerfile
    ports:
      - "80:80"
    networks:
      - mysql-phpmyadmin-employee


volumes:
  db_data:

networks:
  mysql-phpmyadmin-employee:


# docker compose up -d
# http://localhost:8080

# docker compose ps

# docker compose down