

services:
# Database
  bdd:
    container_name: bdd
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABSE: employee
    networks:
      - mysql-phpmyadmin


# phpmyadmin
  phpmyadmin:
    depends_on:
      - bdd
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: bdd
    networks:
      - mysql-phpmyadmin
    

# back
  spring-docker-container:
    container_name: springboot
    ports:
        - "8080:8080"
    build:
      context: ./back_employee
      dockerfile: Dockerfile
    depends_on:
        - bdd
    networks:
        - mysql-phpmyadmin
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://bdd:3306/employee

# front
  react-nginx:
      build:
        context: ./front_employee
        dockerfile: dockerfile
      container_name: react-nginx
      ports:
        - "80:80"
      depends_on:
        - spring-docker-container
      networks:
        - mysql-phpmyadmin


networks:
  mysql-phpmyadmin:

volumes:
  db_data:

# docker-compose up -d